FROM openjdk:17-jdk
#ARG MYSQL_USERNAME=root
#ENV MYSQL_USERNAME="${MYSQL_USERNAME}"
#ARG MYSQL_PASSWORD=mysql123
#ENV MYSQL_PASSWORD="${MYSQL_PASSWORD}"
#ARG MYSQL_ROOT_PASSWORD=mysql123
#ENV MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
#ENV MYSQL_ROOT_PASSWORD=mysql123
#VOLUME /vl
EXPOSE 8080
COPY target/jdbconnectivity-0.0.1-SNAPSHOT.jar app.jar
#ENTRYPOINT ["java","-jar","/app.jar"]
CMD ["java", "-jar", "app.jar"]
